version: '3.8'

services:
  dylan:
    build: .
    container_name: dylan
    restart: unless-stopped
    cap_add:
      - NET_RAW
    ports:
      - "8080:80"

    volumes:
      - ./data:/app/data:rw
      - ./scripts:/app/scripts:ro
      - ./plugins:/app/plugins:ro

    environment:
      - PORT=80
      - RUBY_ENV=production
      - TZ=Europe/Berlin
